name: Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --timeout 5m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
